on: [push]

name: CI for 'either-list-function' library

jobs:
  build:
    name: Build and test the packages
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      matrix:
        ghc:
          - '9.0.1'
          - '8.10.1'
          - '8.8.1'
          - '8.6.5'

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Build
        run: cabal build all
      - name: Test
        run: cabal test all
