on: [push]

name: CI for 'either-list-function' library

jobs:
  build:
    name: Build and test the packages
    runs-on: ubuntu-latest

    continue-on-error: true

    strategy:
      matrix:
        ghc: ['8.6', '8.8', '8.10', '9.0', '9.2']

    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Build
        run: cabal build all
      - name: Test
        run: cabal test all
